### ISSUE TITLE
剧本执行报错

### ISSUE THREAD

**Issue by ghost** [zbnio/zbn#10]
`    run_exec(socket=socket, uuid=uuid)`
`  File "core.py", line 138, in core.run_exec`
`  File "core.py", line 69, in core.get_app_data`
`  File "core.py", line 50, in core.execute`
`UnboundLocalError: local variable 'import_path' referenced before assignment`

点击开始按钮后，报错信息如上。烦请支持。

![image](https://user-images.githubusercontent.com/19603442/99365103-cf97e600-28f1-11eb-8f06-5cc9e1ccad7e.png)

**Comment by sanjinhub** [comment]
请更新到 v0.1.1
