### ISSUE TITLE
项目首次运行报错

### ISSUE THREAD

**Issue by JIMhackKING** [zbnio/zbn#5]
`ImportError: /root/zbn/app/core/linux/core.so: undefined symbol: PyInterpreterState_GetID`

![image](https://user-images.githubusercontent.com/23214854/99223711-ff76b900-281f-11eb-8252-98f45b9e0f8c.png)

系统：Ubuntu 18.04.3 LTS
python 版本：3.6.9（是不是一定要3.7才能用？）

**Comment by sanjinhub** [comment]
请更新到 3.7.7+
